/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;
import java.util.*;
/**
 *
 * @author derekwu
 */
public class DMenuSpecifications extends javax.swing.JFrame {
    private ArrayList<String> toppings;
    private ArrayList<String> drinks;
    private ArrayList<Double> prices;
    private ArrayList<String> sizes;
    /**
     * Creates new form MTMenuSpecifications
     */
    public DMenuSpecifications() {
        toppings = new ArrayList<String> ();
        sizes = new ArrayList<String> ();
        initComponents();
    }
    public DMenuSpecifications(ArrayList<String> a, ArrayList<Double> b) {
        toppings = new ArrayList<String> ();
        sizes = new ArrayList<String> ();       
        drinks = a;
        prices = b;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ToppingsList = new javax.swing.JTextArea();
        ToppingsL = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        PriceOfToppings = new javax.swing.JTextField();
        Sizes = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        SizeList = new javax.swing.JTextArea();
        DrinkSizes = new javax.swing.JLabel();
        SizePrice = new javax.swing.JTextField();
        Finish = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 440));
        setResizable(false);
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Kohinoor Bangla", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(250, 250, 250));
        Title.setText("Menu Specifications");
        getContentPane().add(Title);
        Title.setBounds(220, 50, 180, 28);

        ToppingsList.setColumns(20);
        ToppingsList.setRows(5);
        jScrollPane1.setViewportView(ToppingsList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 130, 244, 84);

        ToppingsL.setForeground(new java.awt.Color(250, 250, 250));
        ToppingsL.setText("Toppings (separated by commas and a space): ");
        getContentPane().add(ToppingsL);
        ToppingsL.setBounds(10, 110, 300, 16);

        Price.setForeground(new java.awt.Color(250, 250, 250));
        Price.setText("Price of Toppings:");
        getContentPane().add(Price);
        Price.setBounds(340, 110, 120, 16);
        getContentPane().add(PriceOfToppings);
        PriceOfToppings.setBounds(340, 130, 70, 26);

        Sizes.setForeground(new java.awt.Color(250, 250, 250));
        Sizes.setText("Cup Sizes (separated by commas and a space): ");
        getContentPane().add(Sizes);
        Sizes.setBounds(10, 240, 310, 16);

        SizeList.setColumns(20);
        SizeList.setRows(5);
        jScrollPane2.setViewportView(SizeList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 260, 244, 84);

        DrinkSizes.setForeground(new java.awt.Color(250, 250, 250));
        DrinkSizes.setText("Prices to Increase Cup Size: ");
        getContentPane().add(DrinkSizes);
        DrinkSizes.setBounds(340, 240, 176, 16);
        getContentPane().add(SizePrice);
        SizePrice.setBounds(340, 260, 70, 26);

        Finish.setText("Finish");
        Finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishActionPerformed(evt);
            }
        });
        getContentPane().add(Finish);
        Finish.setBounds(150, 370, 270, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/black background.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 600, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishActionPerformed
        String a = ToppingsList.getText();
        separate(a);
        prices.add(Double.parseDouble(PriceOfToppings.getText()));
        ToppingsList.setText("");
        PriceOfToppings.setText("");
        String b = SizeList.getText();
        separate2(b);
        prices.add(Double.parseDouble(SizePrice.getText()));
        SizeList.setText("");
        SizePrice.setText("");
        System.out.println(toppings);
        System.out.println(drinks);
        System.out.println(prices);
        System.out.println(sizes);
        setVisible(false);
        new MenuFrame(toppings, drinks, prices ,sizes).setVisible(true);
    }//GEN-LAST:event_FinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DMenuSpecifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DMenuSpecifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DMenuSpecifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DMenuSpecifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DMenuSpecifications().setVisible(true);
            }
        });
    }
    public void separate (String a) {
        while(a.contains(",")){
            int index = a.indexOf(",");
            toppings.add(a.substring(0,index));
            a = a.substring(index + 2);
        }
        toppings.add(a);
    }
    public void separate2 (String a) {
        while(a.contains(",")){
            int index = a.indexOf(",");
            sizes.add(a.substring(0,index));
            a = a.substring(index + 2);
        }
        sizes.add(a);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DrinkSizes;
    private javax.swing.JButton Finish;
    private javax.swing.JLabel Price;
    private javax.swing.JTextField PriceOfToppings;
    private javax.swing.JTextArea SizeList;
    private javax.swing.JTextField SizePrice;
    private javax.swing.JLabel Sizes;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel ToppingsL;
    private javax.swing.JTextArea ToppingsList;
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
