/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author derekwu
 */
public class MenuGenerator2 extends javax.swing.JFrame {

    /**
     * Creates new form MenuGenerator2
     */
    public MenuGenerator2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        View = new javax.swing.JButton();
        DessertButton = new javax.swing.JButton();
        SitDownButton = new javax.swing.JButton();
        NoneButton = new javax.swing.JButton();
        MilkTeaButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setSize(new java.awt.Dimension(600, 430));
        setLayout(null);

        title.setFont(new java.awt.Font("Kohinoor Bangla", 0, 18)); // NOI18N
        title.setForeground(new java.awt.Color(250, 250, 250));
        title.setText("Pick Menu Type");
        add(title);
        title.setBounds(230, 70, 130, 20);

        View.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        View.setText("View");
        add(View);
        View.setBounds(540, 0, 60, 29);

        DessertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icre cream final.png"))); // NOI18N
        add(DessertButton);
        DessertButton.setBounds(50, 110, 120, 170);

        SitDownButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/sitdown final.png"))); // NOI18N
        add(SitDownButton);
        SitDownButton.setBounds(240, 110, 130, 170);

        NoneButton.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        NoneButton.setText("None of the Above");
        add(NoneButton);
        NoneButton.setBounds(200, 340, 220, 50);

        MilkTeaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/milk tea 3 final.png"))); // NOI18N
        MilkTeaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkTeaButtonActionPerformed(evt);
            }
        });
        add(MilkTeaButton);
        MilkTeaButton.setBounds(430, 110, 130, 170);

        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("Dessert Joint");
        add(jLabel1);
        jLabel1.setBounds(70, 290, 81, 16);

        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Sit-Down Restaurant");
        add(jLabel2);
        jLabel2.setBounds(240, 290, 140, 16);

        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("Milk Tea Place");
        add(jLabel3);
        jLabel3.setBounds(450, 290, 90, 16);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(547, 400, 50, 29);

        background.setFont(new java.awt.Font("Kohinoor Bangla", 0, 13)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/black background.jpg"))); // NOI18N
        add(background);
        background.setBounds(0, 0, 600, 430);
    }// </editor-fold>//GEN-END:initComponents

    private void MilkTeaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkTeaButtonActionPerformed
        setVisible(false);
        new MilkTeaGenerator().setVisible(true);
       
    }//GEN-LAST:event_MilkTeaButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGenerator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGenerator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGenerator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGenerator2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGenerator2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DessertButton;
    private javax.swing.JButton MilkTeaButton;
    private javax.swing.JButton NoneButton;
    private javax.swing.JButton SitDownButton;
    private javax.swing.JButton View;
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
