/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author derekwu
 */
public class MenuGenerator3 extends javax.swing.JFrame {

    /**
     * Creates new form MenuGenerator3
     */
    public MenuGenerator3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        Desert = new javax.swing.JButton();
        MilkTea = new javax.swing.JButton();
        SitDown = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        NOne = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backgroun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 444));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 440));
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Kohinoor Bangla", 0, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(250, 250, 250));
        Title.setText("Pick Menu Type");
        getContentPane().add(Title);
        Title.setBounds(240, 60, 140, 28);

        Desert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/icre cream final.png"))); // NOI18N
        Desert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesertActionPerformed(evt);
            }
        });
        getContentPane().add(Desert);
        Desert.setBounds(60, 110, 120, 160);

        MilkTea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/milk tea 3 final.png"))); // NOI18N
        MilkTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MilkTeaActionPerformed(evt);
            }
        });
        getContentPane().add(MilkTea);
        MilkTea.setBounds(430, 110, 124, 160);

        SitDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/sitdown final.png"))); // NOI18N
        SitDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SitDownActionPerformed(evt);
            }
        });
        getContentPane().add(SitDown);
        SitDown.setBounds(240, 110, 120, 160);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(520, 400, 75, 29);

        NOne.setText("None of the Above");
        getContentPane().add(NOne);
        NOne.setBounds(200, 350, 200, 50);

        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("Dessert Joint");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 280, 90, 16);

        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Sit-Down Restaurant");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 280, 140, 16);

        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("Milk Tea Place");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(450, 280, 100, 16);

        backgroun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/black background.jpg"))); // NOI18N
        getContentPane().add(backgroun);
        backgroun.setBounds(0, 0, 600, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MilkTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MilkTeaActionPerformed
        setVisible(false);
        new MilkTeaGenerator().setVisible(true);
    }//GEN-LAST:event_MilkTeaActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void SitDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SitDownActionPerformed
        setVisible(false);
        new SitDownGenerator().setVisible(true);
    }//GEN-LAST:event_SitDownActionPerformed

    private void DesertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesertActionPerformed
        setVisible(false);
        new DesertGenerator().setVisible(true);
    }//GEN-LAST:event_DesertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGenerator3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGenerator3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGenerator3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGenerator3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGenerator3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Desert;
    private javax.swing.JButton Exit;
    private javax.swing.JButton MilkTea;
    private javax.swing.JButton NOne;
    private javax.swing.JButton SitDown;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel backgroun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
